spring:
  application:
    name: ratingservice
  profile:
    active: default
  config:
    import: optional:configserver:http://localhost:8084

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-nzmagm11qqjt38mo.us.auth0.com/
